apiVersion: apps/v1
kind: Deployment
metadata:
  name: plugin-combination
  labels:
    app: plugin-combination
spec:
  replicas: 3
  selector:
    matchLabels:
      app: plugin-combination
      pipecd.dev/variant: primary
  template:
    metadata:
      labels:
        app: plugin-combination
        pipecd.dev/variant: primary
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: helloworld
        image: gcr.io/pipecd/helloworld:v0.9.0
        args:
          - server
        ports:
        - containerPort: 9085

